// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbavVuC2rh59wvLBeupSteUMoDlvmlprs',
    appId: '1:748132747775:web:7eb87b3b8b99fa7116ffca',
    messagingSenderId: '748132747775',
    projectId: 'health-monitoring-app-92d67',
    authDomain: 'health-monitoring-app-92d67.firebaseapp.com',
    storageBucket: 'health-monitoring-app-92d67.appspot.com',
    measurementId: 'G-FN3EYWL92B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB8Cdn8o2ZKqm9wLVI9tN-L97qgz65mPI',
    appId: '1:748132747775:android:81a9b829993987ef16ffca',
    messagingSenderId: '748132747775',
    projectId: 'health-monitoring-app-92d67',
    storageBucket: 'health-monitoring-app-92d67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGh3piHOsgdceU6QsWerQJrUhEzY8zzT8',
    appId: '1:748132747775:ios:c01e1c8f0f998a9816ffca',
    messagingSenderId: '748132747775',
    projectId: 'health-monitoring-app-92d67',
    storageBucket: 'health-monitoring-app-92d67.appspot.com',
    iosClientId: '748132747775-b0cvt8l9rcp6knri3e3v9b40e4gpnjuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmsc23Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGh3piHOsgdceU6QsWerQJrUhEzY8zzT8',
    appId: '1:748132747775:ios:c01e1c8f0f998a9816ffca',
    messagingSenderId: '748132747775',
    projectId: 'health-monitoring-app-92d67',
    storageBucket: 'health-monitoring-app-92d67.appspot.com',
    iosClientId: '748132747775-b0cvt8l9rcp6knri3e3v9b40e4gpnjuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmsc23Project',
  );
}
